name: Termux x86_64 CI
on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  termux-x86_64:
    runs-on: ubuntu-24.04
    # Run the job *inside* the Termux image (no nested docker run)
    container:
      image: termux/termux-docker:x86_64
      # optional, but helps on some hosts
      options: --security-opt seccomp=unconfined

    steps:
      - name: DNS readiness (match your GitLab loop)
        shell: bash
        run: |
          set -eux
          echo "Checking DNS readiness..."
          max_attempts=$((2 * 60 / 5))
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            if curl -Is https://termux.dev >/dev/null 2>&1; then
              echo "DNS is ready."
              break
            fi
            if [ $attempt -eq $max_attempts ]; then
              echo "Timeout: DNS still not ready."
              exit 1
            fi
            attempt=$((attempt + 1))
            sleep 5
          done

      - name: Update apt & install curl
        run: |
          apt update -y
          apt install -y curl

      - name: Run installer (mirror to your GitLab line)
        run: |
          bash <(curl -fsSL https://gitlab.com/gushmazuko/metasploit_in_termux/-/raw/${GITHUB_REF_NAME#refs/heads/}/metasploit.sh)

      - name: Smoke test
        run: msfconsole -v
